test:1.26:
  script: &test_script
  - rustc --version && cargo --version
  - cargo test --all --all-features --verbose
  image: liuchong/rustup:1.26.0

test:stable:
  script: *test_script
  image: liuchong/rustup:stable

test:beta:
  script: *test_script
  image: liuchong/rustup:beta

test:nightly:
  script: *test_script
  image: liuchong/rustup:nightly

clippy:
  script:
  - rustc --version && cargo --version
  - cargo install clippy
  - cargo clippy --all --all-features --verbose
  image: liuchong/rustup:nightly

rustfmt:
  script:
  - rustc --version && cargo --version
  - rustup component add rustfmt-preview
  - cargo fmt -- --check
  image: liuchong/rustup:nightly

pages:
  stage: deploy
  script:
  - cargo doc --all-features
  - mv target/doc public
  - |
    echo "
      <!DOCTYPE html>
      <title>Redirection page</title>
      <meta http-equiv=refresh content='0; url=result_float/'>
      <p> Please check out <a href="result_float/">result_float</a> documentation.
    " > public/index.html
  artifacts:
    paths:
    - public
  image: liuchong/rustup:nightly
  only:
  - master
