test:1.43:
  script: &test_script
  - &print_version rustc --version && cargo --version
  - cargo test --all --all-features --verbose
  image: rust:1.43

test:stable:
  script: *test_script
  image: rust:latest

test:nightly:
  script: *test_script
  image: rustlang/rust:nightly

clippy:
  script:
  - *print_version
  - rustup component add clippy-preview
  - cargo clippy --all --all-features --verbose
  image: rustlang/rust:nightly

rustfmt:
  script:
  - *print_version
  - rustup component add rustfmt-preview
  - cargo fmt -- --check
  image: rustlang/rust:nightly

pages:
  stage: deploy
  script:
  - *print_version
  - cargo doc --all-features
  - mv target/doc public
  - |
    echo "
      <!DOCTYPE html>
      <title>Redirection page</title>
      <meta http-equiv=refresh content='0; url=result_float/'>
      <p> Please check out <a href='result_float/'>result_float</a> documentation.
    " > public/index.html
  artifacts:
    paths:
    - public
  image: rustlang/rust:nightly
  only:
  - master
